/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SolutionsTrackingRouteImport } from './routes/solutions.tracking'
import { Route as SolutionsRecoveryEnterpriseRouteImport } from './routes/solutions.recovery-enterprise'
import { Route as SolutionsRecoveryBusinessRouteImport } from './routes/solutions.recovery-business'
import { Route as SolutionsRecoveryRouteImport } from './routes/solutions.recovery'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SolutionsTrackingRoute = SolutionsTrackingRouteImport.update({
  id: '/solutions/tracking',
  path: '/solutions/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRecoveryEnterpriseRoute =
  SolutionsRecoveryEnterpriseRouteImport.update({
    id: '/solutions/recovery-enterprise',
    path: '/solutions/recovery-enterprise',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsRecoveryBusinessRoute =
  SolutionsRecoveryBusinessRouteImport.update({
    id: '/solutions/recovery-business',
    path: '/solutions/recovery-business',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsRecoveryRoute = SolutionsRecoveryRouteImport.update({
  id: '/solutions/recovery',
  path: '/solutions/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/solutions/recovery': typeof SolutionsRecoveryRoute
  '/solutions/recovery-business': typeof SolutionsRecoveryBusinessRoute
  '/solutions/recovery-enterprise': typeof SolutionsRecoveryEnterpriseRoute
  '/solutions/tracking': typeof SolutionsTrackingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/solutions/recovery': typeof SolutionsRecoveryRoute
  '/solutions/recovery-business': typeof SolutionsRecoveryBusinessRoute
  '/solutions/recovery-enterprise': typeof SolutionsRecoveryEnterpriseRoute
  '/solutions/tracking': typeof SolutionsTrackingRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/solutions/recovery': typeof SolutionsRecoveryRoute
  '/solutions/recovery-business': typeof SolutionsRecoveryBusinessRoute
  '/solutions/recovery-enterprise': typeof SolutionsRecoveryEnterpriseRoute
  '/solutions/tracking': typeof SolutionsTrackingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/solutions/recovery'
    | '/solutions/recovery-business'
    | '/solutions/recovery-enterprise'
    | '/solutions/tracking'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/solutions/recovery'
    | '/solutions/recovery-business'
    | '/solutions/recovery-enterprise'
    | '/solutions/tracking'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/solutions/recovery'
    | '/solutions/recovery-business'
    | '/solutions/recovery-enterprise'
    | '/solutions/tracking'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SolutionsRecoveryRoute: typeof SolutionsRecoveryRoute
  SolutionsRecoveryBusinessRoute: typeof SolutionsRecoveryBusinessRoute
  SolutionsRecoveryEnterpriseRoute: typeof SolutionsRecoveryEnterpriseRoute
  SolutionsTrackingRoute: typeof SolutionsTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/solutions/tracking': {
      id: '/solutions/tracking'
      path: '/solutions/tracking'
      fullPath: '/solutions/tracking'
      preLoaderRoute: typeof SolutionsTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/recovery-enterprise': {
      id: '/solutions/recovery-enterprise'
      path: '/solutions/recovery-enterprise'
      fullPath: '/solutions/recovery-enterprise'
      preLoaderRoute: typeof SolutionsRecoveryEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/recovery-business': {
      id: '/solutions/recovery-business'
      path: '/solutions/recovery-business'
      fullPath: '/solutions/recovery-business'
      preLoaderRoute: typeof SolutionsRecoveryBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/recovery': {
      id: '/solutions/recovery'
      path: '/solutions/recovery'
      fullPath: '/solutions/recovery'
      preLoaderRoute: typeof SolutionsRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  SolutionsRecoveryRoute: SolutionsRecoveryRoute,
  SolutionsRecoveryBusinessRoute: SolutionsRecoveryBusinessRoute,
  SolutionsRecoveryEnterpriseRoute: SolutionsRecoveryEnterpriseRoute,
  SolutionsTrackingRoute: SolutionsTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
